export const LOGOUT = "LOGOUT"
export const ACCOUNT_SETTINGS_DATA = "ACCOUNT_SETTINGS_DATA"
export const ACCOUNT_SETTINGS_PHOTO = "ACCOUNT_SETTINGS_PHOTO"
export const ADD_ROOM_FOR_GAME = "ADD_ROOM_FOR_GAME"